const {createRequire}=require('node:module');const {readFileSync,readdirSync}=require('node:fs');const {DatabaseSync}=require('node:sqlite');const assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');const req=createRequire(root+'/package.json');const ts=req('typescript');const db=new DatabaseSync(':memory:');
for(const f of readdirSync(root+'/migrations').filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync(root+'/migrations/'+f,'utf8'));
const wrap=(sql,args=[])=>({bind:(...values)=>wrap(sql,values),first:async()=>db.prepare(sql).get(...args)??null,sql,args});
const raw={prepare:wrap,batch:async stmts=>{db.exec('BEGIN');try{const result=stmts.map(s=>{const stmt=db.prepare(s.sql);if(/^\s*SELECT/i.test(s.sql))return {results:stmt.all(...s.args)};const r=stmt.run(...s.args);return {meta:{changes:Number(r.changes)}}});db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}};
const source=readFileSync(root+'/server/board.ts','utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const mod={exports:{}};new Function('require','module','exports',code)(name=>name==='@/db/raw'?{database:()=>raw}:req(name),mod,mod.exports);const board=mod.exports;
const workerCode=ts.transpileModule(readFileSync(root+'/server/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const workerMod={exports:{}};new Function('require','module','exports',workerCode)(name=>name==='./board'?board:req(name),workerMod,workerMod.exports);
const env={DB:raw,ALLOWED_ORIGINS:'https://example.test'};
const worker=workerMod.exports.default;
const api={GET:()=>worker.fetch(new Request('https://api.test/api/board',{headers:{origin:'https://example.test'}}),env),POST:request=>worker.fetch(request,env)};
const post=async p=>{const r=await api.POST(new Request('https://example.test/api/board',{method:'POST',headers:{origin:'https://example.test','Content-Type':'application/json'},body:JSON.stringify(p)}));return {status:r.status,body:await r.json()}};
const row=()=>db.prepare("SELECT * FROM vehicles WHERE id='initial-1'").get();
(async()=>{
let cors=await worker.fetch(new Request('https://api.test/api/board',{method:'OPTIONS',headers:{origin:'https://example.test'}}),env);assert.equal(cors.status,204);assert.equal(cors.headers.get('Access-Control-Allow-Origin'),'https://example.test');
cors=await worker.fetch(new Request('https://api.test/api/board',{headers:{origin:'https://untrusted.test'}}),env);assert.equal(cors.status,403);assert.equal(cors.headers.get('Access-Control-Allow-Origin'),null);
await api.GET();const base={id:'initial-1',actor:'입력자',stage:'after'};const update=async p=>post({...base,revision:row().revision,...p});
let r=await update({action:'balance',balance:54000,reservation:{enabled:true,date:'2099-10-05',name:'예약자'}});assert.equal(r.status,200);assert.equal(row().reservation_name,'예약자');assert.equal(row().actor,'입력자');
r=await update({action:'balance',balance:59000,actor:'다른 사람',reservation:{enabled:true,date:'2099-10-05',name:'예약자'}});assert.equal(r.status,200);assert.equal(row().reservation_date,'2099-10-05');
r=await update({action:'balance',balance:50000});assert.equal(r.status,200);assert.equal(row().reservation_name,'예약자');
const rev=row().revision;r=await update({action:'balance',balance:60000,reservation:{enabled:true,date:'',name:''}});assert.equal(r.status,200);assert.equal(row().reservation_name,null);assert.equal(row().reservation_date,null);
r=await post({...base,revision:rev,action:'balance',balance:50000,reservation:{enabled:true,date:'2099-10-05',name:'옛 예약'}});assert.equal(r.status,409);assert.equal(row().balance,60000);
await update({action:'balance',balance:30000,reservation:{enabled:true,date:'2099-10-06',name:'홍길동'}});
const oldTime=row().updated;r=await update({action:'reservation',reservation:{enabled:false}});assert.equal(r.status,200);assert.equal(row().balance,30000);assert.equal(row().updated,oldTime);assert.equal(row().reservation_name,null);assert.equal(row().reservation_date,null);
r=await update({action:'reservation',reservation:{enabled:true,date:'2099-02-30',name:'홍길동'}});assert.equal(r.status,400);
r=await update({action:'reservation',reservation:{enabled:true,date:'2099-10-07',name:''}});assert.equal(r.status,400);
r=await update({action:'reservation',reservation:{enabled:true,date:'2099-10-07',name:'직접 입력'}});assert.equal(r.status,200);assert.equal(row().reservation_name,'직접 입력');
const h=db.prepare('SELECT * FROM history ORDER BY rowid DESC LIMIT 1').get();assert.equal(h.reservation_name,'직접 입력');assert.equal(h.reservation_date,'2099-10-07');
console.log('PASS: real API + SQLite: create, keep below threshold (including old client), clear at 60000, cancel without balance change, conflict protection, invalid date/name rejected, history saved.');
})().catch(e=>{console.error(e);process.exit(1)});
