declare global { interface Window { HIPASS_CONFIG?: { apiBaseUrl?: string } } }
function apiUrl(){const base=window.HIPASS_CONFIG?.apiBaseUrl?.trim().replace(/\/$/,'');if(!base)throw new Error('공유 저장소 연결이 필요합니다. 관리자에게 문의해 주세요.');const url=new URL(base);if(url.protocol!=='https:'&&url.hostname!=='localhost'&&url.hostname!=='127.0.0.1')throw new Error('저장소 주소를 확인해 주세요.');return base+'/api/board'}
import { useEffect,useState,useCallback } from 'react';
import { Car, Plus, Pencil, RefreshCw, CreditCard, Trash2, History, UserRound, ArrowUpRight, TriangleAlert, MoreHorizontal, CalendarDays } from 'lucide-react';
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { RadioGroup,RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel } from '@/components/ui/alert-dialog';
type Vehicle={id:string;name:string;balance:number|null;stage:'before'|'after'|null;approximate:number;reservation_date:string|null;reservation_name:string|null;actor:string|null;updated:string|null;revision:number};
type Entry={id:string;name:string;action:string;balance:number|null;stage:'before'|'after'|null;approximate:number;reservation_date:string|null;reservation_name:string|null;actor:string;time:string};
const stageLabel=(s:string|null)=>s==='before'?'출발 전':s==='after'?'도착 후':'시점 미기록';
const money=(n:number)=>n.toLocaleString('ko-KR');
const date=(s:string)=>new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}).format(new Date(s));
export default function Home(){
const [vehicles,setVehicles]=useState<Vehicle[]>([]),[history,setHistory]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[actor,setActor]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<{action:string;v?:Vehicle}|null>(null),[value,setValue]=useState(''),[formError,setFormError]=useState(''),[stage,setStage]=useState(''),[reserved,setReserved]=useState(false),[reserveDate,setReserveDate]=useState(''),[reserveName,setReserveName]=useState('');
const refresh=useCallback(async()=>{try{const r=await fetch(apiUrl(),{cache:'no-store'}),d=await r.json() as {vehicles:Vehicle[];history:Entry[];error:string};if(!r.ok)throw Error(d.error);setVehicles(d.vehicles);setHistory(d.history);setError('');return d;}catch(e){setError((e as Error).message||'연결 상태를 확인해 주세요.');return null;}finally{setLoading(false)}},[]);
useEffect(()=>{try{setActor(localStorage.getItem('hipass-actor')||'')}catch{};refresh();const timer=setInterval(refresh,15000);const focus=()=>refresh();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[refresh]);
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:'read_vehicle_balances',description:'Refresh and read the shared vehicle balances and recent changes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');const d=await refresh();if(!d)throw Error('Balances unavailable');return d;}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[refresh]);
function loadReservation(v?:Vehicle){setReserved(!!v?.reservation_date);setReserveDate(v?.reservation_date??'');setReserveName(v?.reservation_name??'')}
function open(action:string,v?:Vehicle){loadReservation(v);if(action==='reservation'&&!v?.reservation_date)setReserved(true);setFormError('');setStage('');setValue(action==='rename'?v!.name:'');setModal({action,v});setNotice('')}
async function save(){if(!modal)return;const action=modal.action;const savedActor=(action==='reservation'?reserveName:actor).trim();if(!savedActor){setFormError('입력자 이름을 입력해 주세요.');return}if(action==='balance'&&!stage){setFormError('출발 전 또는 도착 후를 선택해 주세요.');return}if(action==='balance'&&(!/^\d+$/.test(value)||Number(value)>100000)){setFormError('잔액은 0~100,000 사이의 숫자를 천원 단위로 입력해 주세요.');return}if(action==='reservation'&&reserved&&(!reserveName.trim()||!reserveDate)){setFormError('충전 예정일과 예약자 이름을 입력해 주세요.');return}if(action==='reservation'&&!reservationChanged){setFormError('예약 내용을 변경해 주세요.');return}setBusy(true);setFormError('');try{const r=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:modal.v?.id,revision:modal.v?.revision,name:value,balance:action==='balance'?Number(value)*1000:undefined,stage:action==='balance'?stage:undefined,reservation:action==='reservation'?{enabled:reserved,date:reserveDate,name:reserveName}:undefined,actor:savedActor})});const d=await r.json() as {vehicles:Vehicle[];history:Entry[];error:string};if(!r.ok){if(r.status===409){const fresh=await refresh();const v=fresh?.vehicles.find((v:Vehicle)=>v.id===modal.v?.id);if(v){setModal({...modal,v});loadReservation(v);}}throw Error(d.error)}try{localStorage.setItem('hipass-actor',savedActor);setActor(savedActor)}catch{}setModal(null);setNotice('저장했습니다.');await refresh()}catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
const effectiveBalance=value!==''&&/^\d+$/.test(value)?Number(value)*1000:modal?.v?.balance;
const clearByAmount=modal?.action==='balance'&&value!==''&&effectiveBalance!==null&&effectiveBalance!==undefined&&effectiveBalance>=60000;
const reservationChanged=reserved!==!!modal?.v?.reservation_date||(reserved&&(reserveDate!==(modal?.v?.reservation_date??'')||reserveName.trim()!==(modal?.v?.reservation_name??'')));
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fields=<><label className="field">입력자 이름<input maxLength={30} value={actor} onChange={e=>setActor(e.target.value)} placeholder="예: 홍길동" required/></label><p className="hint">직접 입력한 이름으로 기록됩니다.</p>{formError&&<p className="error" role="alert">{formError}</p>}</>;
return <><header className="top"><div className="brand"><span className="brand-icon"><CreditCard size={23}/></span><span className="brand-title">인천중부지사 배차 하이패스 잔액 공유</span></div><span className="top-label">우리 차량 잔액 관리</span></header><main><div className="heading"><div><h1>하이패스 잔액</h1></div><button className="primary" onClick={()=>open('add')}><Plus size={18}/>차량 추가</button></div><div className="section-head"><h2>차량별 잔액 <span>{vehicles.length}</span></h2><button className="text-button" onClick={refresh} aria-label="잔액 새로고침"><RefreshCw size={16}/>새로고침</button></div>{error&&<div className="error" role="alert">{error}</div>}{notice&&<p className="success" role="status">{notice}</p>}{loading?<div className="empty">잔액을 불러오는 중입니다.</div>:<section className="cars" aria-label="전체 차량 잔액">{vehicles.map(v=><article className={"vehicle-row"+(v.balance!==null&&v.balance<60000?" needs-recharge":"")} key={v.id}>
<div className="vehicle-name"><h3>{v.name}</h3>{v.balance!==null&&v.balance<60000?<span className="warning-badge" role="status"><TriangleAlert size={15} aria-hidden="true"/>충전 필요</span>:<span className="balance-caption">{v.balance===null?'잔액을 입력해 주세요':'마지막 확인 잔액'}</span>}</div>
<div className={'vehicle-balance '+(v.balance===null?'unknown':'')}>{v.balance!==null&&!!v.approximate&&<span className="approx-prefix">약 </span>}{v.balance===null?'미입력':money(v.balance)}{v.balance!==null&&<small>원</small>}</div>
{v.reservation_date&&<p className={"reservation-line"+(v.reservation_date<today?" overdue":"")}>📅 {v.reservation_date.slice(5).replace('-','/')} · {v.reservation_name} · {v.reservation_date<today?'예약일 지남':'충전 예정'}</p>}<div className="vehicle-bottom"><div className="vehicle-record">{v.actor?<><strong>{v.actor}<span className="stage-tag">{stageLabel(v.stage)}</span></strong><span>{date(v.updated!)} 확인</span></>:<span>입력 기록 없음</span>}</div><button className="edit-balance" onClick={()=>open('balance',v)} aria-label={`${v.name} 잔액 입력`}><Pencil size={15}/>잔액 입력</button><DropdownMenu><DropdownMenuTrigger asChild><button className="vehicle-more" aria-label={`${v.name} 관리`}><MoreHorizontal size={21}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>open('rename',v)}><Pencil/>차량명 변경</DropdownMenuItem><DropdownMenuItem variant="destructive" onSelect={()=>open('delete',v)}><Trash2/>차량 삭제</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
<div className="reservation-actions"><button className={"reserve-button"+(v.reservation_date?" is-reserved":"")} onClick={()=>open('reservation',v)} aria-label={`${v.name} ${v.reservation_date?'충전 예약 확인 및 변경':'충전예약하기'}`}><CalendarDays size={16}/>{v.reservation_date?'예약 확인·변경':'충전예약하기'}</button></div></article>)}</section>}{!loading&&!error&&!vehicles.length&&<div className="empty">등록된 차량이 없습니다. 차량을 추가해 주세요.</div>}<section className="recharge-guide" aria-label="하이패스 충전 안내"><CreditCard size={25}/><div><strong>잔액이 5만원대 이하라면 충전해 주세요.</strong><p>충전을 위해 행정지원팀에서 카드를 받아 가세요.</p><span>충전 장소: <b>인천대교</b></span></div></section><p className="footnote">마지막 확인 잔액입니다. 이후 운행에 따라 달라질 수 있습니다. 새 기록은 천원 미만을 버린 대략적인 금액입니다.</p><section className="history"><div className="section-head"><h2><History size={19}/>최근 변경 이력</h2><span className="hint">최근 100건 · 한국 시간</span></div>{history.length?history.map(h=><div className="history-row" key={h.id}><span className="history-avatar">{h.actor.slice(0,1)}</span><div className="history-info"><strong>{h.name}</strong><p>{h.actor} · {({add:'차량 추가',rename:'차량명 변경',delete:'차량 삭제',balance:'잔액 입력',reservation:'충전 예약 변경'} as Record<string,string>)[h.action]}{h.action==='balance'&&` · ${stageLabel(h.stage)}`}</p>{h.reservation_date&&<p>충전 예정: {h.reservation_date} · {h.reservation_name}</p>}{h.action==='reservation'&&!h.reservation_date&&<p>예약 해제</p>}</div><div className="history-right">{h.action==='balance'&&<strong>{h.approximate?'약 ':''}{money(h.balance!)}원</strong>}<time>{date(h.time)}</time></div></div>):<div className="empty">차량 정보를 입력하면 변경 이력이 여기에 남습니다.</div>}</section><footer>15초마다 최신 기록을 확인합니다.</footer></main><Dialog open={!!modal&&modal.action!=='delete'} onOpenChange={o=>{if(!o&&!busy)setModal(null)}}><DialogContent className={modal?.action==='reservation'?'reservation-dialog':undefined}><DialogTitle>{modal?.action==='add'?'차량 추가':modal?.action==='rename'?'차량명 변경':modal?.action==='reservation'?`${modal?.v?.name} 충전 예약`:`${modal?.v?.name} 잔액 입력`}</DialogTitle><DialogDescription>{modal?.action==='balance'?'충전한 금액이 아닌, 카드에 남은 전체 잔액을 입력하세요.':modal?.action==='reservation'?'충전 예정일과 예약자 이름을 입력하세요.':'차량번호나 알아보기 쉬운 이름을 입력하세요.'}</DialogDescription><form onSubmit={e=>{e.preventDefault();save()}}>{modal?.action==='balance'?<>
<fieldset className="stage-field"><legend>확인 시점 <span>잔액 입력 시 필수</span></legend><RadioGroup value={stage} onValueChange={setStage} className="stage-options" aria-label="잔액 확인 시점" required><label className={stage==='before'?'selected':''}><RadioGroupItem value="before" id="stage-before"/>출발 전</label><label className={stage==='after'?'selected':''}><RadioGroupItem value="after" id="stage-after"/>도착 후</label></RadioGroup></fieldset>
<label className="field" htmlFor="balance-thousands">현재 잔액 <span className="hint">천원 단위</span></label><div className="amount-entry"><input id="balance-thousands" required autoFocus value={value} maxLength={6} inputMode="numeric" pattern="[0-9]+" onChange={e=>setValue(e.target.value)} placeholder="예: 54" aria-describedby="amount-guide amount-preview"/><span>천원</span></div><p id="amount-guide" className="hint amount-guide">천원 미만은 빼고 입력하세요. 54,730원 → <b>54</b><br/>1,000원 미만은 0으로 입력하세요.</p><div id="amount-preview" className="amount-preview" aria-live="polite">{/^\d+$/.test(value)&&Number(value)<=100000?<><strong>약 {money(Number(value)*1000)}원</strong>으로 저장됩니다.{Number(value)<60&&<span className="preview-warning"><TriangleAlert size={15}/>충전 필요</span>}</>:'숫자를 입력하면 저장될 금액이 표시됩니다.'}</div>
{modal?.v?.reservation_date&&<p className="reservation-reset" role="status">{clearByAmount?<><strong>예약도 함께 해제됩니다.</strong><br/>6만원 이상으로 저장하면 예약자 이름과 예정일이 초기화됩니다.</>:<>충전 예약: {modal.v.reservation_date} · {modal.v.reservation_name}<br/>6만원 미만으로 저장하면 예약은 유지됩니다.</>}</p>}
</>:modal?.action==='reservation'?<section className="reservation-form" aria-label="충전 예약">
<label className="reservation-check"><Checkbox checked={reserved} onCheckedChange={checked=>{const next=checked===true;setReserved(next);if(!next){setReserveName('');setReserveDate('')}}}/>충전 예약</label>
<div className="reservation-fields">
{reserved&&<label className="field">충전 예정일<input type="date" value={reserveDate} min={modal?.v?.reservation_date&&modal.v.reservation_date<today?modal.v.reservation_date:today} onChange={e=>setReserveDate(e.target.value)} required/></label>}
<label className="field">{reserved?'예약자 이름':'취소자 이름'}<input value={reserveName} maxLength={30} placeholder="예: 홍길동" onChange={e=>setReserveName(e.target.value)} required/></label>
</div>
{reserved?<p className="reservation-note">잔액을 6만원 이상으로 저장하면 자동 해제됩니다.{modal?.v?.reservation_date&&<><br/>취소하려면 위 체크를 해제하세요.</>}</p>:<p className="reservation-reset" role="status">저장하면 예약이 취소되고 예정일·예약자 이름이 삭제됩니다.</p>}
</section>:<label className="field">차량명<input autoFocus value={value} maxLength={40} onChange={e=>setValue(e.target.value)} placeholder="예: 업무차량 1234" required/></label>}{modal?.action==='reservation'?(formError&&<p className="error" role="alert">{formError}</p>):fields}<button className="primary save" disabled={busy}>{busy?'저장 중…':modal?.action==='reservation'?(reserved?'예약 저장':'예약 취소 저장'):'저장하기'}</button></form></DialogContent></Dialog><AlertDialog open={modal?.action==='delete'} onOpenChange={o=>{if(!o&&!busy)setModal(null)}}><AlertDialogContent><AlertDialogTitle>{modal?.v?.name}을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>차량 목록에서 삭제되며, 기존 변경 이력은 보관됩니다.</AlertDialogDescription>{fields}<div className="dialog-actions"><AlertDialogCancel disabled={busy}>취소</AlertDialogCancel><button className="danger" disabled={busy} onClick={save}>{busy?'삭제 중…':'차량 삭제'}</button></div></AlertDialogContent></AlertDialog></>}
